version: 0.2
            
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Start runtime build...
    finally:
      - echo Finaly runtime build...
  pre_build:
    commands:
      - echo Start Pre build...
      - aws s3 mb s3://bucket-deploy-lambda-abbi --region us-east-1
    finally:
      - echo Finaly Pre build...
  build:
    commands:
      - echo iniciando build
      - echo Entering build phase...
      - echo Build started on `date`   
      - mvn package shade:shade
    finally:
      - aws cloudformation package --template-file template.yaml --s3-bucket bucket-deploy-lambda-abbi --output-template template-api-aws-lambda-export.yaml
      - aws cloudformation deploy --template-file template-api-aws-lambda-export.yaml --stack-name api-aws-lambda-stack --capabilities CAPABILITY_NAMED_IAM
  post_build:
    commands:
      - echo Start Pos build...
    finally:
      - echo Finally Pos build...
artifacts:
  files:
    - template-api-aws-lambda-export.yaml