AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A app java created for SAM CLI.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  AppFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./target/api-aws-lambda-1.0.jar
      Description: Cloud formation created lambda for demo-xray-lambda
      Handler: br.com.aws.handle.AppHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      TracingConfig: 
        Mode: Active
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          STAGE: prod
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /init
            Method: get
      DependsOn:
        - api-aws-lambda-stack-AppFunctionRole-CSNFW81HJVBP
 
  api-aws-lambda-stack-AppFunctionRole-CSNFW81HJVBP:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Action: "sts:AssumeRole"
      Principal:
        Service: lambda.amazonaws.com
      Effect: Allow
      Policies:
        PolicyName: demo-xray-lambda-policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
            Effect: Allow
            Resource: "*"       
        
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AppApi:
    Description: "API Gateway endpoint URL for Prod stage for App function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AppFunction:
    Description: "App Api Lambda Function ARN"
    Value: !GetAtt AppFunction.Arn
  AppFunctionIamRole:
    Description: "Implicit IAM Role created for App Api function"
    Value: !GetAtt AppFunctionRole.Arn
